Title:  Part II - Configuration
Author: Venelin Valkov
Date:   29.05.2012

**If you didn't get a change to see the first part of the series go to [Make 2D Game for Desktop, Android and iOS with Moai and Rapanui – Part I Introduction][1]**

[1]: http://www.makeyourown2dgame.com/tutorial/make-2d-game-for-desktop-android-and-ios-with-moai-and-rapanui-part-i-introduction/ "Make 2D Game for Desktop, Android and iOS with Moai and Rapanui – Part I Introduction"

In this part of the series we are going get ourselves an editor and configure
Moai SDK and Rapanui.

# Picking editor

You can use editor of your choice but we went with [Notepad++][2].

[2]:http://notepad-plus-plus.org/ "Notepad++"

# Configuration

In this part I am going to walk you through
the process of running a sample from the Rapanui SDK.
First we are going to get some Moai stuff, mix them with Rapanui
and create something really nice.

# Project files

In order to help you get up and running quickly
you can directly download project files for each part [Here][3].

[3]:https://github.com/bapplz/makeyourown2dgame "Project Files"

# Resources

These are the sites used in the screencast:

[Notepad++](http://notepad-plus-plus.org/ "Notepad++")
[Mac OS How to configure Moai](https://github.com/moai/moai-beta "Mac OS How to configure Moai")
[Project Files](https://github.com/bapplz/makeyourown2dgame "Project Files")

