Title:  Part I - Introduction
Author: Venelin Valkov
Date:   29.05.2012

In this tutorial series we are going to build a 2d game for desktop, Android and iOS devices using Lua, Moai and Rapanui.

# What We Are Creating

In this part of the screencast I am going to show you
what game we are going to build using Moai and Rapanui

# Register Moai Account

In this part I am going to walk you through
the process of registering a Moai account

# Download Moai and Rapanui

Here we are going to download all the necessary libraries 
for getting up and running quickly

# Resources

These are the sites used in the screencast

[Moai SDK](http://getmoai.com/ "Moai SDK")
[Rapanui SDK](https://github.com/ymobe/rapanui "Rapanui SDK")
