Title:  Part III - Starting Up
Author: Venelin Valkov
Date:   4.06.2012

**If you didn't get a change to see the second part of the series go to [Android, iPhone and iPad 2D Game Development – Part II Configuration][1]**

[1]: http://www.makeyourown2dgame.com/tutorial/android-iphone-and-ipad-2d-game-development-part-ii-configuration/ "Android, iPhone and iPad 2D Game Development – Part II Configuration"

In this part of the series we are going to draw the paddle, actually move it and get ourselves a nice ball on the screen!
Of course we are going to use Moai and Rapanui to create our own 2D game!

# Drawing the paddle

Let's see how to draw an actual object to the screen using Moai and Rapanui.
It looks pretty easy!

# Moving the paddle

The paddle is cool but still static. Let's make it move!

# Drawing the ball

Now it is time to draw the ball. That is pretty easy, just like 
we did with the paddle. Some code reordening will happen though!

# Project files

In order to help you get up and running quickly
you can directly download project files for each part [Here][2].

[2]:https://github.com/bapplz/makeyourown2dgame "Project Files"

# Resources

These are the sites used in the screencast:

[Make Your Own 2D Game](http://www.makeyourown2dgame.com/ "Make Your Own 2D Game")
[Project Files](https://github.com/bapplz/makeyourown2dgame "Project Files")

