Title:  Part IV - Moving It
Author: Venelin Valkov
Date:   08.06.2012

**If you didn't get a change to see the third part of the series go to [Android, iPhone and iPad 2D Game Development – Part III Starting Up][1]**

[1]: http://www.makeyourown2dgame.com/tutorial/android-iphone-and-ipad-2d-game-development-part-iii-starting-up/ "Android, iPhone and iPad 2D Game Development – Part III Starting Up"

In the fourth part of this series we using the Moai SDK and Rapanui SDK we are going to 
draw the bricks and actually move the ball in our little bricks 2d game.

# Drawing the bricks

Using a Lua table we are going to draw and store
each and every brick in different color - it is a game after all!

# Preparing the ball

Let's choose the speed of the ball and the initial direction!

# Moving the ball

The title speaks for itself. I like to move it!

# Project files

In order to help you get up and running quickly
you can directly download project files for each part [Here][2].

[2]:https://github.com/bapplz/makeyourown2dgame "Project Files"

# Resources

These are the sites used in the screencast:

[Make Your Own 2D Game](http://www.makeyourown2dgame.com/ "Make Your Own 2D Game")
[Project Files](https://github.com/bapplz/makeyourown2dgame "Project Files")

