Title:  Part V - Collision
Author: Venelin Valkov
Date:   18.06.2012

**If you didn't get a change to see the fourth part of the series go to [Android, iPhone and iPad 2D Game Development – Part IV Moving It][1]**

[1]: http://www.makeyourown2dgame.com/tutorial/android-iphone-and-ipad-2d-game-development-part-iv-moving-it/ "Android, iPhone and iPad 2D Game Development – Part IV Moving It"

It is time to break some bricks and make our 2D Game bounce. Collision is the theme of this video! There
is not much of assistance that Moai SDK or Rapanui SDK will provide but we will keep it going!

# Paddle Collision

It is quite natural for the ball to be hitted by the paddle.
Let's detect when this happens and make it happen!

# World Collision

Chasing the ball of the screen is not a good experience for the gamer. Let's fix that!

# Bricks Collision

This is the meaty part! Let them bricks be scared!

# Project files

In order to help you get up and running quickly
you can directly download project files for each part [Here][2].

[2]:https://github.com/bapplz/makeyourown2dgame "Project Files"

# Resources

These are the sites used in the screencast:

[Make Your Own 2D Game](http://www.makeyourown2dgame.com/ "Make Your Own 2D Game")
[Project Files](https://github.com/bapplz/makeyourown2dgame "Project Files")
[Great Article on Collision Detection](http://www.wildbunny.co.uk/blog/2011/04/20/collision-detection-for-dummies/ "Great Article on Collision Detection")
[Another Great Article on Collision Detection](http://www.gamasutra.com/view/feature/3190/advanced_collision_detection_.php "Another Great Article on Collision Detection")

